#!/bin/sh

function autostart {
	# stop all existing autostart processes then restart them
	# programs: sxhkd, tint2, polybar, dunst
	killall sxhkd &
	killall tint2 &
	killall polybar &
	killall dunst &
	sxhkd -c ~/.config/sxhkd/sxhkdrc_bspwm ~/.config/sxhkd/sxhkdrc.common &
	nvidia-settings --load-config-only &
	dunst &
	tint2 &
	~/.config/polybar/active/launch.sh &
	echo 'autostart end'

}

function configure_borders {
	# setup border width, colors and gaps
	bspc config border_width         2
	bspc config window_gap          16
	bspc config top_padding 28
	bspc config bottom_padding 0
	bspc config normal_border_color	"#4B5263"
	bspc config active_border_color	"#56B6C2"
	bspc config focused_border_color "#61AFEF"
	bspc config presel_feedback_color	"#C678DD"
#	bspc config urgent_border_color "#E06C75"
	echo 'borders end'

}

function configure_workspaces {
	# set workspace names and monitors
	bspc monitor DVI-I-0 -d           
	bspc monitor HDMI-0 -d  
	echo 'monitors end'

}

function configure_mouse_actions {
	# set mouse actions move, resize_side, resize_corner
	bspc config pointer_action1 move
	bspc config pointer_action2 resize_side
	bspc config pointer_action3 resize_corner
	echo 'mouse end'

}

function configure_rules {

	# delete all rules
	bspc rule -r "*"
	
	# set windowsize for scratchpad windows
	windowwidth=1000
	windowheight=500

	screenwidth=1920
	screenheight=1080
	windowx=$(($screenwidth/2-$windowwidth/2))
#	windowy=$(($screenheight/2-$windowheight/2))
	windowy=28


	bpsc rule -a '*' state=pseudo_tiled
	# make scratchpad floating and set size
	bspc rule -a KeePassXC state=floating rectangle=$windowwidth'x'$windowheight'+'$windowx'+'$windowy” sticky=on
	bspc rule -a alacritty:Scratchpad state=floating rectangle=$windowwidth'x'$windowheight'+'$windowx'+'$windowy” 

	bspc rule -a mpv desktop=^8
	bspc rule -a mpv state=pseudo_tiled
	bspc rule -a Thunderbird desktop=^5
	bpsc rule -a alacritty state=tiled



	echo 'rules end'
}

function configure_layout {
	# set default split ratio
	bspc config split_ratio          0.52
	# set monocle mode options
	bspc config borderless_monocle   true
	bspc config gapless_monocle      true
	echo 'layout end'

}

function setup_floating_desktop {

	FLOATING_DESKTOP_ID=$(bspc query -D -d '^4')

	bspc subscribe node_add | while read -a msg ; do
		desk_id=${msg[2]}
		wid=${msg[4]}
		[ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
	done
	echo 'float end'

}

###
configure_workspaces
configure_borders
configure_layout
configure_mouse_actions
configure_rules
#setup_floating_desktop
autostart
# usefull / needed for java applications (MatLab)
wmname LG3D &
